apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: mjbright/k8s-demo:py
        imagePullPolicy: Always
        name: k8s-demo
        volumeMounts:
        - name: config
          mountPath: /etc/k8s-demo
          # NOTE: A container using a ConfigMap as a subPath volume will not receive ConfigMap updates.

      volumes:
      - configMap:
          name: k8s-demo-py
        name: config

